;MyTools.text, subset of ToolTraps.Text sufficient for MacPaint
;--------------------------------------------------------------------
;
;   ToolTraps is the Pascal/QuickDraw-ToolBox trap interface.
;   It defines all the names declared external in the interface
;   code, and implements them by trapping with the "auto-pop" bit
;   set to remove the extra return address on the stack
;   before dispatching.  Most of this file was generated by the
;   program "MakeTTraps".
;
;         "written" by Andy Hertzfeld    31-Oct-82
;
;   MODIFICATION HISTORY:
;
;     21-Nov-82  AJH  regenerated for ROM 1.8
;     01-Dec-82  AJH  changes for ROM 1.9
;     13-Feb-83  AJH  regenerated for ROM 2.0
;     16-Mar-83  AJH  updated for ROM 2.4
;     20-Apr-83  BLH  Changed dialog proc names for ROM 3.0
;      4-May-83  BLH  Added new resource procs for ROM 3.0
;     28-May-83  SC   Added text edit stuff and changed dialog
;     03-Jun-83  AJH  Regenerated for ROM 4.0
;     08-Jun-83  SC   Changed AlertSound to ErrorSound
;     13-Jun-83  AJH  Added InsertResMenu, OpenDeskAcc
;     04-Aug-83  SC   Added TEInsert, TEGetText, TESetJust
;     04-Aug-83  SC   Added SystemBeep, DrawGrow
;     06-Aug-83  SC   Added HandAndHand, PtrAndHand
;     06-Aug-83  BLH  Removed EndSubResource.  Changed BeginSubResource to
;                      HomeResFile.  Added GetFinderInfo, SetFinderInfo
;                      at the end.
;     12-Aug-83  AJH  Added DragGrayRgn
;     16-Aug-83  SC   Added scrap stuff
;     18-Aug-83  BLH  Removed GetFinderInfo, SetFinderInfo.
;      2-Sep-83  SC   Removed Bytes stuff (It should be an OS).
;
;--------------------------------------------------------------------

                .PROC   TTraps,0
;

                .DEF   InitCurs
InitCurs        .WORD   $AC50


                .DEF   SetCurso
SetCurso        .WORD   $AC51


                .DEF   HideCurs
HideCurs        .WORD   $AC52


                .DEF   ShowCurs
ShowCurs        .WORD   $AC53


                .DEF   ShieldCu
ShieldCu        .WORD   $AC55


                .DEF   ObscureC
ObscureC        .WORD   $AC56


                .DEF   BitAnd
BitAnd          .WORD   $AC58


                .DEF   BitShift
BitShift        .WORD   $AC5C


                .DEF   BitTst
BitTst          .WORD   $AC5D


                .DEF   BitSet
BitSet          .WORD   $AC5E


                .DEF   BitClr
BitClr          .WORD   $AC5F


                .DEF   GetPixel
GetPixel        .WORD   $AC65


                .DEF   FixRatio
FixRatio        .WORD   $AC69


                .DEF   HiWord
HiWord          .WORD   $AC6A


                .DEF   LoWord
LoWord          .WORD   $AC6B


                .DEF   InitGraf
InitGraf        .WORD   $AC6E


                .DEF   OpenPort
OpenPort        .WORD   $AC6F


                .DEF   LocalToG
LocalToG        .WORD   $AC70


                .DEF   GlobalTo
GlobalTo        .WORD   $AC71


                .DEF   SetPort
SetPort         .WORD   $AC73


                .DEF   GetPort
GetPort         .WORD   $AC74


                .DEF   SetPortB
SetPortB        .WORD   $AC75


                .DEF   SetOrigi
SetOrigi        .WORD   $AC78


                .DEF   ClipRect
ClipRect        .WORD   $AC7B


                .DEF   ClosePor
ClosePor        .WORD   $AC7D


                .DEF   AddPt
AddPt           .WORD   $AC7E


                .DEF   SubPt
SubPt           .WORD   $AC7F


                .DEF   SetPt
SetPt           .WORD   $AC80


                .DEF   EqualPt
EqualPt         .WORD   $AC81


                .DEF   DrawChar
DrawChar        .WORD   $AC83


                .DEF   DrawStri
DrawStri        .WORD   $AC84


                .DEF   TextFont
TextFont        .WORD   $AC87


                .DEF   TextMode
TextMode        .WORD   $AC89


                .DEF   TextSize
TextSize        .WORD   $AC8A


                .DEF   GetFontI
GetFontI        .WORD   $AC8B


                .DEF   StringWi
StringWi        .WORD   $AC8C


                .DEF   CharWidt
CharWidt        .WORD   $AC8D


                .DEF   LineTo
LineTo          .WORD   $AC91


                .DEF   Line
Line            .WORD   $AC92


                .DEF   MoveTo
MoveTo          .WORD   $AC93


                .DEF   Moov
Moov            .WORD   $AC94


                .DEF   HidePen
HidePen         .WORD   $AC96


                .DEF   ShowPen
ShowPen         .WORD   $AC97


                .DEF   PenSize
PenSize         .WORD   $AC9B


                .DEF   PenMode
PenMode         .WORD   $AC9C


                .DEF   PenPat
PenPat          .WORD   $AC9D


                .DEF   PenNorma
PenNorma        .WORD   $AC9E


                .DEF   FrameRec
FrameRec        .WORD   $ACA1


                .DEF   PaintRec
PaintRec        .WORD   $ACA2


                .DEF   EraseRec
EraseRec        .WORD   $ACA3


                .DEF   InvertRe
InvertRe        .WORD   $ACA4


                .DEF   FillRect
FillRect        .WORD   $ACA5


                .DEF   EqualRec
EqualRec        .WORD   $ACA6


                .DEF   SetRect
SetRect         .WORD   $ACA7


                .DEF   OffSetRe
OffSetRe        .WORD   $ACA8


                .DEF   InSetRec
InSetRec        .WORD   $ACA9


                .DEF   SectRect
SectRect        .WORD   $ACAA


                .DEF   Pt2Rect
Pt2Rect         .WORD   $ACAC


                .DEF   PtInRect
PtInRect        .WORD   $ACAD


                .DEF   EmptyRec
EmptyRec        .WORD   $ACAE


                .DEF   FrameRou
FrameRou        .WORD   $ACB0


                .DEF   PaintRou
PaintRou        .WORD   $ACB1


                .DEF   FrameOva
FrameOva        .WORD   $ACB7


                .DEF   PaintOva
PaintOva        .WORD   $ACB8


                .DEF   PackBits
PackBits        .WORD   $ACCF


                .DEF   UnpackBi
UnpackBi        .WORD   $ACD0


                .DEF   PaintRgn
PaintRgn        .WORD   $ACD3


                .DEF   NewRgn
NewRgn          .WORD   $ACD8


                .DEF   DisposeR
DisposeR        .WORD   $ACD9


                .DEF   OpenRgn
OpenRgn         .WORD   $ACDA


                .DEF   CloseRgn
CloseRgn        .WORD   $ACDB


                .DEF   RectRgn
RectRgn         .WORD   $ACDF


                .DEF   OffSetRg
OffSetRg        .WORD   $ACE0


                .DEF   EmptyRgn
EmptyRgn        .WORD   $ACE2


                .DEF   PtInRgn
PtInRgn         .WORD   $ACE8


                .DEF   RectInRg
RectInRg        .WORD   $ACE9


                .DEF   CopyBits
CopyBits        .WORD   $ACEC


                .DEF   ScrollRe
ScrollRe        .WORD   $ACEF


                .DEF   SetStdPr
SetStdPr        .WORD   $ACEA


                .DEF   StdText
StdText         .WORD   $AC82


                .DEF   PicComme
PicComme        .WORD   $ACF2


                .DEF   OpenPict
OpenPict        .WORD   $ACF3


                .DEF   ClosePic
ClosePic        .WORD   $ACF4


                .DEF   KillPict
KillPict        .WORD   $ACF5


                .DEF   DrawPict
DrawPict        .WORD   $ACF6


                .DEF   MapPt
MapPt           .WORD   $ACF9


                .DEF   MapRect
MapRect         .WORD   $ACFA


                .DEF   InitFont
InitFont        .WORD   $ACFE


                .DEF   GetFontN
GetFontN        .WORD   $ACFF


                .DEF   GetFNum
GetFNum         .WORD   $AD00


                .DEF   RealFont
RealFont        .WORD   $AD02


                .DEF   SetFontL
SetFontL        .WORD   $AD03


                .DEF   InitWind
InitWind        .WORD   $AD12


                .DEF   NewWindo
NewWindo        .WORD   $AD13


                .DEF   ShowWind
ShowWind        .WORD   $AD15


                .DEF   HideWind
HideWind        .WORD   $AD16


                .DEF   SetWTitl
SetWTitl        .WORD   $AD1A


                .DEF   TrackGoA
TrackGoA        .WORD   $AD1E


                .DEF   SelectWi
SelectWi        .WORD   $AD1F


                .DEF   BeginUpD
BeginUpD        .WORD   $AD22


                .DEF   EndUpDat
EndUpDat        .WORD   $AD23


                .DEF   ValidRec
ValidRec        .WORD   $AD2A


                .DEF   FindWind
FindWind        .WORD   $AD2C


                .DEF   InitMenu
InitMenu        .WORD   $AD30


                .DEF   InsertMe
InsertMe        .WORD   $AD35


                .DEF   DrawMenu
DrawMenu        .WORD   $AD37


                .DEF   HiliteMe
HiliteMe        .WORD   $AD38


                .DEF   EnableIt
EnableIt        .WORD   $AD39


                .DEF   DisableI
DisableI        .WORD   $AD3A


                .DEF   MenuSele
MenuSele        .WORD   $AD3D


                .DEF   MenuKey
MenuKey         .WORD   $AD3E


                .DEF   SetItemS
SetItemS        .WORD   $AD42


                .DEF   CheckIte
CheckIte        .WORD   $AD45


                .DEF   GetItem
GetItem         .WORD   $AD46


                .DEF   AddResMe
AddResMe        .WORD   $AD4D


                .DEF   CountMIt
CountMIt        .WORD   $AD50

                .DEF   ShowCont
ShowCont        .WORD   $AD57


                .DEF   HideCont
HideCont        .WORD   $AD58


                .DEF   TrackCon
TrackCon        .WORD   $AD68


                .DEF   FindCont
FindCont        .WORD   $AD6C


                .DEF   GetNextE
GetNextE        .WORD   $AD70


                .DEF   GetMouse
GetMouse        .WORD   $AD72


                .DEF   StillDow
StillDow        .WORD   $AD73


                .DEF   TickCoun
TickCoun        .WORD   $AD75


                .DEF   GetKeys
GetKeys         .WORD   $AD76


                .DEF   InitDial
InitDial        .WORD   $AD7B


                .DEF   GetNewDi
GetNewDi        .WORD   $AD7C


                .DEF   DisposDi
DisposDi        .WORD   $AD83


                .DEF   Alert
Alert           .WORD   $AD85


                .DEF   ModalDia
ModalDia        .WORD   $AD91


                .DEF   GetResou
GetResou        .WORD   $ADA0


                .DEF   SystemCl
SystemCl        .WORD   $ADB3


                .DEF   SystemTa
SystemTa        .WORD   $ADB4


                .DEF   OpenDeskAcc
OpenDeskAcc     .WORD   $ADB6


                .DEF   GetCurso
GetCurso        .WORD   $ADB9


                .DEF   GetStrin
GetStrin        .WORD   $ADBA


                .DEF   GetPictu
GetPictu        .WORD   $ADBC


                .DEF   GetNewCo
GetNewCo        .WORD   $ADBE


                .DEF   GetMenu
GetMenu         .WORD   $ADBF


                .DEF    SystemEdit
SystemEdit      .WORD   $ADC2

                .DEF   SystemBe
SystemBe        .WORD   $ADC8

                .DEF   TEInit
TEInit          .WORD   $ADCC


                .DEF   TextBox
TextBox         .WORD   $ADCE


                .DEF   UnLoadSe
UnLoadSe        .WORD   $ADF1


                .DEF   ExitToSh
ExitToSh        .WORD   $ADF4


                .DEF   InfoScra
InfoScra        .WORD  $ADF9

                .DEF   UnloadSc
UnloadSc        .WORD  $ADFA

                .DEF   ZeroScra
ZeroScra        .WORD  $ADFC

                .DEF   GetScrap
GetScrap        .WORD  $ADFD


                .END
